### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by lh11117** [win12-online/win12#284]
## 描述

可以使用表达提交issues

像[这个仓库](https://github.com/godotengine/godot)的issues提交方式这样：
<img width="738" alt="image" src="https://github.com/tjy-gitnub/win12/assets/99455215/84854096-a090-4706-819c-177323dc4d3c">

## 方案

`.github\ISSUE_TEMPLATE\提出建议.yml`：
```
name: 提出建议
description: 请向我们提出宝贵的建议
body:

- type: textarea
  attributes:
    label: 描述
    description: >
     请简要描述一下建议
  validations:
    required: true

- type: textarea
  attributes:
    label: 方案
    description: >
     请在这里提出施行建议的方案或希望有的功能
  validations:
    required: true

- type: textarea
  attributes:
    label: 其他
    description: >
     如果有其他的内容，请在这里进行补充

```

`.github\ISSUE_TEMPLATE\漏洞反馈.yml`：
```
name: 漏洞汇报
description: 请向我们汇报您在使用过程中发现的漏洞
body:

- type: textarea
  attributes:
    label: 描述
    description: >
     请描述一下这个漏洞是什么样的
  validations:
    required: true

- type: textarea
  attributes:
    label: 重现
    description: >
     请用步骤的方式描述一下如何重新复现该漏洞
  validations:
    required: true


- type: textarea
  attributes:
    label: 截图
    description: >
     如果有的话，请在上面的文本框附上相关的截图或视频

- type: markdown
  attributes:
    value: |
     # 测试环境

- type: input
  attributes:
    label: 浏览器
    description: >
     请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等
    placeholder: chrome
  validations:
    required: true

- type: input
  attributes:
    label: 浏览器版本
    description: >
     请在这里填入浏览器的版本
    placeholder: 115.x.x.x
  validations:
    required: true

- type: input
  attributes:
    label: 操作系统
    description: >
     请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等
    placeholder: Windows NT 10.0
  validations:
    required: true


- type: textarea
  attributes:
    label: 其他
    description: >
     如果有其他的内容，请在这里进行补充


```

## 其他

记得删除`.github\ISSUE_TEMPLATE\漏洞汇报.md`和`.github\ISSUE_TEMPLATE\提出建议.md`

**Comment by NebulaTechs** [comment]
好哒~

**Comment by NebulaTechs** [comment]
对了，回复机器人有吗

**Comment by NB-Group** [comment]
可以的，小伙子好建议

**Comment by lh11117** [comment]
对了，再添加一个：
`新闻投稿.yml`:
```
name: 投稿新闻
description: 投稿“小组件”里的新闻
body:

- type: textarea
  attributes:
    label: 新闻标题
    description: >
     简单写一下新闻的标题
  validations:
    required: true

- type: textarea
  attributes:
    label: 内容
    description: >
     写一下新闻的内容
  validations:
    required: true

- type: textarea
  attributes:
    label: 图片
    description: >
     在下面的文本框上传新闻图片
  validations:
    required: true
  

```
