### ISSUE TITLE
[建议]我想免费给win12提供国内加速访问支持（免费托管 win12.programcx.cn）

### ISSUE THREAD

**Issue by ProgramCX** [win12-online/win12#547]
## 描述
众所周知，github.io 由于服务器在国外，以及一些网络限制，导致 tjy-gitnub.github.io/win12/desktop.html 访问速度较慢，影响用户体验。

我目前拥有 阿里云 ECS 服务器（3 年 99 元续费），主要用于托管我的个人博客和一些小项目（如烟花网站）。服务器资源还有富余，因此 希望**免费**提供国内加速服务，让 win12 项目可以更快地被国内用户访问。

我可以为 win12 项目提供 win12.programcx.cn 或 win12.pinsoftstd.cn 作为国内访问域名，并使用 GitHub Actions 自动同步 GitHub Pages 版本，以保证两个站点内容一致。

> ⚠ 说明：我不会投放任何广告，网站的内容控制权完全交给该项目的主要贡献者。如果你们愿意，也可以在 Bing 和百度上推广该域名。

服务器参数：

![Image](https://github.com/user-attachments/assets/a3926e14-8bd0-4250-bfb8-734854310704)

域名：

![Image](https://github.com/user-attachments/assets/9bacec8a-5d10-4aa9-89df-47190c92979c)

**都已经被备案了**：[皖ICP备2024067408号](https://beian.miit.gov.cn/)、[皖ICP备2024067408号-1](https://beian.miit.gov.cn/)

## 方案
我配置好域名解析和nginx配置文件，向 CertBot 申请 ssl 后，就可以使用Github Workflow使得两个网站保持时刻同步：
1. 新建工作流

![Image](https://github.com/user-attachments/assets/85238944-ff2a-44a6-9c0a-dfbda9922d0a)

2. 配置 GitHub Secrets，其中包含我的服务器的ip地址、ssh端口、用户名和私钥，以便通过 rsync 部署

![Image](https://github.com/user-attachments/assets/d292f0e3-0942-412f-bf24-eedf38dc4252)

3.编写工作流文件代码
```
name: Deploy to Cloud Server

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  # 拉取代码
      uses: actions/checkout@v4

    - name: Deploy to Cloud Server
      uses: burnett01/rsync-deployments@6.0.0
      with:
          switches: -avzr --delete
          path: ./  # 推送整个根目录
          remote_path: /usr/local/nginx/win12-html/  #  服务器的部署目录
          remote_host: ${{ secrets.DEPLOY_HOST }}  # 远程主机 IP
          remote_port: ${{ secrets.DEPLOY_PORT }}  # SSH 端口
          remote_user: ${{ secrets.DEPLOY_USER }}  # SSH 用户
          remote_key: ${{ secrets.DEPLOY_KEY }}  # SSH 私钥

```
4.提交后可以每次 main 分支有 push 后会自动部署到服务器。

## 其他
- 如果你们 愿意接受 这个方案，我可以立即配置服务器，并提供 win12.programcx.cn 这个域名（或 win12.pinsoftstd.cn，如果你们介意是我的个人域名的话），**一切免费**。
- 如果 不需要，也完全没关系，我只是想为这个优秀的项目贡献一点微薄之力 😃
期待你们的回复！🎉
